<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJUFxlvI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJUFxlvI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJUFxlvI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJUFxlvI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJUFxlvI\App_KernelDevDebugContainer([
    'container.build_hash' => 'JUFxlvI',
    'container.build_id' => '68179e2d',
    'container.build_time' => 1610372674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJUFxlvI');
